# This file was generated by GoReleaser. DO NOT EDIT.
cask "starter" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "663a3f9fab98da07e511a5ad33c4b7291e19dc34b7aa95e8b52c2527feb9cac5"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "faac755059de1de4d49167c21c428dde9ff9907046ab276d236197ff68ebaaaf"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "862db0b55103c02aca84ff96c9f89960f06be99562291633a709ab72add79e51"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3520ceadd4e135be3d28d19e9a8534640f297ebf61ed0bd6297fc202b996332e"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "starter"
  desc "Scaffold projects from templates, with an arrow-key picker."
  homepage "https://github.com/madeth1/starter-pack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starter"]
    end
  end

  # No zap stanza required
end
