# This file was generated by GoReleaser. DO NOT EDIT.
cask "starter" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "cff9933062db16d93743b151b7a4ae3094cc9b903d89cf4464c3279109eb7917"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eae8c99f491762bcb2067dabd22af817b8b4aa9d5032e52293ff0916810f7363"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8319112934ae86791060a8e4415add97c5a1d54c1bd07c52fdfc41028d50182d"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "80cdea527241cb63474f109939c6dae29e19906de12bb8670762951812e6587f"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "starter"
  desc "Scaffold projects from templates, with an arrow-key picker."
  homepage "https://github.com/madeth1/starter-pack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starter"]
    end
  end

  # No zap stanza required
end
