# This file was generated by GoReleaser. DO NOT EDIT.
cask "starter" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "252dcb4955929f018a1900a00baf0c2a93977374b8ec9ad099c0e6835297ff02"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "59fbae3827ee4a73348c223919cc4e8c1b6fa27021ebee76e484b8505a206c25"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2edd2040ef2a799430c27af745a61c2aba22d00d06cc57a9d9521eda80960a57"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a7a88fbf5916ef6987b4015e51271674ff221d254a6073054eee5e254e10b2ba"
      url "https://github.com/madeth1/starter-pack/releases/download/v#{version}/starter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "starter"
  desc "Scaffold projects from templates, with an arrow-key picker."
  homepage "https://github.com/madeth1/starter-pack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starter"]
    end
  end

  # No zap stanza required
end
